# TCL File Generated by Component Editor 18.1
# Thu Apr 25 11:35:22 EDT 2019
# DO NOT MODIFY


# 
# fft_accelerator "FFT Accelorator" v1.0
#  2019.04.25.11:35:22
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module fft_accelerator
# 
set_module_property DESCRIPTION ""
set_module_property NAME fft_accelerator
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "FFT Accelorator"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL FFT_Accelerator
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file FFT_Accelerator.sv SYSTEM_VERILOG PATH FFT_Accelerator.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# module assignments
# 
set_module_assignment embeddedsw.dts.group fft
set_module_assignment embeddedsw.dts.name fft_accelerator
set_module_assignment embeddedsw.dts.vendor csee4840


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 writedata writedata Input 8
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 address address Input 8
add_interface_port avalon_slave_0 readdata readdata Output 8
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point FFT
# 
add_interface FFT conduit end
set_interface_property FFT associatedClock clock
set_interface_property FFT associatedReset ""
set_interface_property FFT ENABLED true
set_interface_property FFT EXPORT_OF ""
set_interface_property FFT PORT_NAME_MAP ""
set_interface_property FFT CMSIS_SVD_VARIABLES ""
set_interface_property FFT SVD_ADDRESS_GROUP ""

add_interface_port FFT KEY keyinput Input 4
add_interface_port FFT HEX1 display1 Output 7
add_interface_port FFT HEX0 display0 Output 7
add_interface_port FFT HEX3 display3 Output 7
add_interface_port FFT HEX4 display4 Output 7
add_interface_port FFT HEX5 display5 Output 7
add_interface_port FFT FPGA_I2C_SCLK i2c_clk Output 1
add_interface_port FFT FPGA_I2C_SDAT i2c_data Bidir 1
add_interface_port FFT AUD_XCK aud_xck Output 1
add_interface_port FFT AUD_DACLRCK aud_daclrck Input 1
add_interface_port FFT AUD_ADCLRCK aud_adclrck Input 1
add_interface_port FFT AUD_BCLK aud_bclk Input 1
add_interface_port FFT AUD_ADCDAT aud_adcdat Input 1
add_interface_port FFT AUD_DACDAT aud_dacdat Output 1
add_interface_port FFT HEX2 display2 Output 7

